<a href="https://colab.research.google.com/github/elijahsk/CS5242/blob/master/Copy_of_cs5242_lecture01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# 1. Tensor Construction


In numpy the data is stored in arrays. We call one array as a tensor, which could be a scalar, vector, matrix or higher dimensional array.




In [0]:
# create tensor with matrix list
x = np.array([[1, 2, 3], [4, 5, 6]])
print('x = \n', x)

# create tensor with zeros or ones
x = np.zeros(shape=(2, 4))
print('x = \n', x)
x = np.ones(shape=(2, 4))
print('x = \n', x)

# create tensor with random distribution along with fixed size
y = np.random.normal(loc=0, scale=1, size=(3, 4))
print('y = \n', y)

# you can reproduce the output of random distribution with seeds
np.random.seed(1234)
y1 = np.random.normal(loc=0, scale=1, size=(3, 4))
print('y1 = \n', y1)

np.random.seed(1234)
y2 = np.random.normal(loc=0, scale=1, size=(3, 4))
print('y2 = \n', y2)

x = 
 [[1 2 3]
 [4 5 6]]
x = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
x = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
y = 
 [[ 0.44426901  0.00802872  0.48975512 -2.40482141]
 [-0.28727938  0.45672132  0.03043535  0.65424097]
 [-0.40204053  1.08393754 -0.69372148  0.45288199]]
y1 = 
 [[ 0.47143516 -1.19097569  1.43270697 -0.3126519 ]
 [-0.72058873  0.88716294  0.85958841 -0.6365235 ]
 [ 0.01569637 -2.24268495  1.15003572  0.99194602]]
y2 = 
 [[ 0.47143516 -1.19097569  1.43270697 -0.3126519 ]
 [-0.72058873  0.88716294  0.85958841 -0.6365235 ]
 [ 0.01569637 -2.24268495  1.15003572  0.99194602]]


# 2. Tensor Operations

In [0]:
# scalar operations
x = np.array([1.5])
y = np.array([3])

print('x + y = ', x + y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', np.power(x,y))

x + y =  [4.5]
x * y =  [4.5]
x / y =  [0.5]
x ** y =  [3.375]


In [0]:
# vector operations
v = np.array([1, 2, 3])
u = np.array([-1, -2, -3])
print('np.dot(v, u)=', np.dot(v, u))

print('u + v =', u + v)

np.dot(v, u)= -14
u + v = [0 0 0]


In [0]:
# matrix operations
X = np.array([[1, 2, 3], [4, 5, 6]])
print("X=\n ", X)
Y = np.array([[6, 4, 3], [2, 5, 9]])


print('shape of X = ', X.shape)                   #shape of tensor
print('sum of along 0-axis = ', X.sum(axis=0))    #summation
print('X+Y= \n', X + Y)                           #element-wise addition
print('X * Y = \n', X * Y)                        #element-wise multiplication
print('reshape X as (3,2) = \n', X.reshape(3,2))  #reshape size
print('swap axis of X = \n', X.transpose((1,0)))  #change axis

X=
  [[1 2 3]
 [4 5 6]]
shape of X =  (2, 3)
sum of along 0-axis =  [5 7 9]
X+Y= 
 [[ 7  6  6]
 [ 6 10 15]]
X * Y = 
 [[ 6  8  9]
 [ 8 25 54]]
reshape X as (3,2) = 
 [[1 2]
 [3 4]
 [5 6]]
swap axis of X = 
 [[1 4]
 [2 5]
 [3 6]]


[Matrix multiplication](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)


* If both arguments are 2-D they are multiplied like conventional matrices.
* If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
* If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.


In [0]:
Z = np.array([[2,3], [3,4], [4,5]])
v = np.array([1, 2, 3])

print('np.matmul(X, Z) shape is ', np.matmul(X, Z).shape)
print('np.matmul(X, v) shape is ', np.matmul(X, v).shape)

np.matmul(X, Z) shape is  (2, 2)
np.matmul(X, v) shape is  (2,)


Broadcasting rules from [cs231n](http://cs231n.github.io/python-numpy-tutorial/#numpy-broadcasting)

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

This rule applies to the [universal function](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs). Most are element-wise functions.

More details at https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [0]:
x = np.random.rand(2, 3)
y = np.random.rand(2, 1)
z = np.random.rand(3)    # better make the shape explicit, (3, 1)  or (1, 3)


print('x is \n', x)
print('y is \n', y)
print('z is \n', z)
print('x + y is \n', x + y)
print('x + y shape is ', (x + y).shape)  #broadcast addition
print('x * z is \n', x * z)
print('x * z shape is ', (x * z).shape)  #broadcast addition

x is 
 [[0.01840676 0.16184026 0.81743596]
 [0.83817576 0.74623645 0.13825706]]
y is 
 [[0.86601291]
 [0.20512351]]
z is 
 [0.93880059 0.8571827  0.15702727]
x + y is 
 [[0.88441967 1.02785317 1.68344887]
 [1.04329927 0.95135996 0.34338057]]
x + y shape is  (2, 3)
x * z is 
 [[0.01728028 0.13872667 0.12835973]
 [0.7868799  0.63966098 0.02171013]]
x * z shape is  (2, 3)


In [0]:
x = np.random.rand(2,3)
y = np.random.rand(2)   # better make the shape explicit, (3, 1)  or (1, 3)
xy = x + y

ValueError: ignored

In [0]:
x = np.random.rand(2, 1, 3)
y = np.random.rand(3, 1, 2, 3)
print('x / y shape is ', (x/y).shape)

x / y shape is  (3, 2, 2, 3)


In [0]:
# Matrix Norm
# More details in https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html
x = np.array([[1, 2, 3], [4, 5, 6]])

print('Frobenius norm = \n', np.linalg.norm(x, ord='fro'))
print('2-norm = \n', np.linalg.norm(x, ord=2))

Frobenius norm = 
 9.539392014169456
2-norm = 
 9.508032000695724


# 3. Gradients Computation
Suppose we have the following computations:

\begin{align}
\boldsymbol{u} & = A\boldsymbol{x} \\
y & = \|\boldsymbol{u}-\boldsymbol{b}\|^2 = (\boldsymbol{u}-\boldsymbol{b})^T(\boldsymbol{u}-\boldsymbol{b})
\end{align}

where $\boldsymbol{x} \in \mathbb{R}^{n \times 1}$, $\boldsymbol{u} \in \mathbb{R}^{m \times 1}$, $\boldsymbol{b} \in \mathbb{R}^{m \times 1}$ are represented as column vectors and $\boldsymbol{b}$ is a constant vector.

Thus, the gradient can be computed as:

\begin{align}
\frac{\partial{\boldsymbol{u}}}{\partial{\boldsymbol{x}}} & = A \\
\frac{\partial{y}}{\partial{\boldsymbol{u}}} & = (\boldsymbol{u} - \boldsymbol{b})^T \\
\frac{\partial{y}}{\partial{\boldsymbol{x}}} & = (\boldsymbol{u} - \boldsymbol{b})^T A
\end{align}

In [0]:
import numpy as np
np.random.seed(1234)
x = np.random.normal(loc=0, scale=1, size=(3, 1))
A = np.random.normal(loc=0, scale=1, size=(2, 3))
b = np.random.normal(loc=0, scale=1, size=(2, 1))
u = np.matmul(A, x)
print('x = \n', x)
print('A = \n', A)
print('u = \n', u)
# a=np.array([np.arange(4), np.arange(4)])
# print(a.shape)
# print(a)
# print((np.transpose(a)))

[[1.9818531 ]
 [1.18581253]]
x = 
 [[ 0.47143516]
 [-1.19097569]
 [ 1.43270697]]
A = 
 [[-0.3126519  -0.72058873  0.88716294]
 [ 0.85958841 -0.6365235   0.01569637]]
(2, 4)
[[0 1 2 3]
 [0 1 2 3]]
[[0 0]
 [1 1]
 [2 2]
 [3 3]]


In [0]:
udx = A
ydu = np.transpose(u - b)
ydx = np.matmul(ydu, A)

print('gradient of u to x = \n', udx)
print('gradient of y to u = \n', ydu)
print('gradient of y to x = \n', ydx)

gradient of u to x = 
 [[-0.3126519  -0.72058873  0.88716294]
 [ 0.85958841 -0.6365235   0.01569637]]
gradient of y to u = 
 [[4.22453805 0.0357768 ]]
gradient of y to x = 
 [[-1.29005651 -3.0669273   3.74841516]]


# Linear regression for a single instance


Using gradient descent algorithm to optimize the objective function

In [0]:
# for a univariate problem with a single instance
def opt(niter=10, alpha=0.1, c1=1, c2=-1, c3=1):
    w=0.1
    for i in range(niter):
        # print J(w)=w*w*c1+w*c2+c3
        Jw = w * w * c1 + w * c2 + c3
        print('Jw={}'.format(Jw))
        
        # compute the gradient of J(w) with respect to w
        gw = 2 * c1 * w + c2
        
        # update w
        w = w - alpha * gw

opt()

Jw=0.91
Jw=0.8524
Jw=0.815536
Jw=0.79194304
Jw=0.7768435456
Jw=0.7671798691839999
Jw=0.76099511627776
Jw=0.7570368744177665
Jw=0.7545035996273705
Jw=0.7528823037615171


In [0]:
# for a multivariate problem with a single instance
def opt(niter=20, alpha=0.01):
    w = np.random.rand(3)
    x = np.array([3, 4, 5])  # feature
    y = 0.9                  # target value
    for i in range(niter):
        # print J(w)=0.5*(np.dot(x, w) - y)**2
        Jw = 0.5 * (np.dot(x, w) - y) ** 2
        print('Jw={}'.format(Jw))
        
        # compute the gradient of J(w) with respect to w
        gw = (np.dot(x, w) - y) * x
        
        # update w
        w = w - alpha * gw

opt() 

Jw=12.654016097683373
Jw=3.163504024420843
Jw=0.7908760061052111
Jw=0.1977190015263027
Jw=0.04942975038157573
Jw=0.012357437595393941
Jw=0.003089359398848481
Jw=0.0007723398497121093
Jw=0.00019308496242802733
Jw=4.827124060700847e-05
Jw=1.2067810151750754e-05
Jw=3.01695253793837e-06
Jw=7.54238134484388e-07
Jw=1.885595336211311e-07
Jw=4.713988340526573e-08
Jw=1.1784970851359044e-08
Jw=2.946242712839761e-09
Jw=7.365606782078096e-10
Jw=1.841401695519524e-10
Jw=4.60350423890534e-11


# Linear regression with multiple instances

We assume the data is generated via

$$ y = w^Tx $$
where w=[0.1, 2, 0.2]

In [0]:
rng = np.random.RandomState(1)
X = 5 * rng.rand(50, 3)
w = np.array([0.1, 2., 0.2])   # ground truth w
y = np.matmul(X, w) + rng.randn(50)
print(X.shape, y.shape)

(50, 3) (50,)


In [0]:

class MyLRModel():
  def __init__(self, niter=50, alpha=0.03):
    self.niter = niter
    self.alpha = alpha
    
  def fit(self, X, y):
    m, n = X.shape    
    self.w = np.random.rand(n)  # initialize w
    
    for i in range(self.niter):
      # Compute loss 
      temp = np.sum(X * self.w, axis = 1) - y
      Jw = 0.5 * np.sum(temp * temp) / m
      print('Jw = {}'.format(Jw))
#       print(temp.shape)  
      # Compute the gradient 
      gw = np.matmul(np.transpose(X), temp) / m
#       print(gw)
        
      # Update self.w
      self.w = self.w - self.alpha * gw
#       print(end='')

      
  def predict(self, X):
      return np.matmul(X, self.w) 


model = MyLRModel()

model.fit(X, y)
print(model.w)



Jw = 6.018602764972609
Jw = 2.6820927245710555
Jw = 1.9600410489823807
Jw = 1.6974288835674778
Jw = 1.530319794218116
Jw = 1.3952181926926404
Jw = 1.2793150586817075
Jw = 1.1785992740260547
Jw = 1.0907958068172772
Jw = 1.0141444590293403
Jw = 0.9471627361168173
Jw = 0.8885784580252227
Jw = 0.8372949421081575
Jw = 0.7923651444493086
Jw = 0.7529702674729387
Jw = 0.7184016287771496
Jw = 0.6880452074319348
Jw = 0.6613684475254074
Jw = 0.637908976174347
Jw = 0.6172649483091573
Jw = 0.5990867752496677
Jw = 0.58307003147267
Jw = 0.5689493654399304
Jw = 0.556493266889831
Jw = 0.5454995653886002
Jw = 0.5357915538471425
Jw = 0.527214646688668
Jw = 0.5196334958638971
Jw = 0.512929499343446
Jw = 0.5069986463978214
Jw = 0.5017496521788093
Jw = 0.49710234107274465
Jw = 0.49298624420034476
Jw = 0.48933938145277994
Jw = 0.48610720271700214
Jw = 0.48324166657082057
Jw = 0.4807004378174202
Jw = 0.47844618786222376
Jw = 0.4764459841816467
Jw = 0.47467075705191886
Jw = 0.47309483334629365
Jw = 0.471695528