<a href="https://colab.research.google.com/github/elijahsk/CS5242/blob/master/cs5242_lecture01_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# 1. Tensor Construction


In numpy the data is stored in arrays. We call one array as a tensor, which could be a scalar, vector, matrix or higher dimensional array.




In [0]:
# create tensor with matrix list
x = np.array([[1, 2, 3], [4, 5, 6]])
print('x = \n', x)

# create tensor with zeros or ones
x = np.zeros(shape=(2, 4))
print('x = \n', x)
x = np.ones(shape=(2, 4))
print('x = \n', x)

# create tensor with random distribution along with fixed size
y = np.random.normal(loc=0, scale=1, size=(3, 4))
print('y = \n', y)

# you can reproduce the output of random distribution with seeds
np.random.seed(1234)
y1 = np.random.normal(loc=0, scale=1, size=(3, 4))
print('y1 = \n', y1)

np.random.seed(1234)
y2 = np.random.normal(loc=0, scale=1, size=(3, 4))
print('y2 = \n', y2)

x = 
 [[1 2 3]
 [4 5 6]]
x = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
x = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
y = 
 [[ 0.99194602  1.32115819 -1.54690555 -0.20264632]
 [-0.65596934  0.19342138  0.55343891  1.31815155]
 [-0.46930528  0.67555409 -1.81702723 -0.18310854]]
y1 = 
 [[ 0.47143516 -1.19097569  1.43270697 -0.3126519 ]
 [-0.72058873  0.88716294  0.85958841 -0.6365235 ]
 [ 0.01569637 -2.24268495  1.15003572  0.99194602]]
y2 = 
 [[ 0.47143516 -1.19097569  1.43270697 -0.3126519 ]
 [-0.72058873  0.88716294  0.85958841 -0.6365235 ]
 [ 0.01569637 -2.24268495  1.15003572  0.99194602]]


# 2. Tensor Operations

In [0]:
# scalar operations
x = np.array([1.5])
y = np.array([3])

print('x + y = ', x + y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', np.power(x,y))

x + y =  [4.5]
x * y =  [4.5]
x / y =  [0.5]
x ** y =  [3.375]


In [0]:
# vector operations
v = np.array([1, 2, 3])
u = np.array([-1, -2, -3])
print('np.dot(v, u)=', np.dot(v, u))

print('u + v =', u + v)

np.dot(v, u)= -14
u + v = [0 0 0]


In [0]:
# matrix operations
X = np.array([[1, 2, 3], [4, 5, 6]])
print("X=\n ", X)
Y = np.array([[6, 4, 3], [2, 5, 9]])


print('shape of X = ', X.shape)   #shape of tensor
print('sum of along 0-axis = ', X.sum(axis=0))    #summation
print('X+Y= \n', X + Y)  #element-wise addition
print('X * Y = \n', X * Y)  #element-wise multiplication
print('reshape X as (3,2) = \n', X.reshape(3,2))    #reshape size
print('swap axis of X = \n', X.transpose((1,0)))     #change axis

X=
  [[1 2 3]
 [4 5 6]]
shape of X =  (2, 3)
sum of along 0-axis =  [5 7 9]
X+Y= 
 [[ 7  6  6]
 [ 6 10 15]]
X * Y = 
 [[ 6  8  9]
 [ 8 25 54]]
reshape X as (3,2) = 
 [[1 2]
 [3 4]
 [5 6]]
swap axis of X = 
 [[1 4]
 [2 5]
 [3 6]]


[Matrix multiplication](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)


* If both arguments are 2-D they are multiplied like conventional matrices.
* If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
* If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.


In [0]:
Z = np.array([[2,3], [3,4], [4,5]])
v = np.array([1, 2, 3])

print('np.matmul(X, Z) shape is ', np.matmul(X, Z).shape)
print('np.matmul(X, v) shape is ', np.matmul(X, v).shape)

np.matmul(X, Z) shape is  (2, 2)
np.matmul(X, v) shape is  (2,)


Broadcasting rules from [cs231n](http://cs231n.github.io/python-numpy-tutorial/#numpy-broadcasting)

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

This rule applies to the [universal function](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs). Most are element-wise functions.

More details at https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [0]:
x = np.random.rand(2, 3)
y = np.random.rand(2, 1)
z = np.random.rand(3)    # better make the shape explicit, (3, 1)  or (1, 3)


print('x + y shape is ', (x + y).shape)  #broadcast addition
print('x * z shape is ', (x * z).shape)  #broadcast multiplication

x + y shape is  (2, 3)
x * z shape is  (2, 3)


In [0]:
x = np.random.rand(2,3)
y = np.random.rand(2)   # better make the shape explicit, (1, 3)
xy = x + y

ValueError: ignored

In [0]:
x = np.random.rand(2, 1, 3)
y = np.random.rand(3, 1, 2, 3)
print('x / y shape is ', (x/y).shape)

x / y shape is  (3, 2, 2, 3)


In [0]:
# Matrix Norm
# More details in https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html
x = np.array([[1, 2, 3], [4, 5, 6]])

print('Frobenius norm = \n', np.linalg.norm(x, ord='fro'))
print('2-norm = \n', np.linalg.norm(x, ord=2))

Frobenius norm = 
 9.539392014169456
2-norm = 
 9.508032000695724


# 3. Gradients Computation
Suppose we have the following computations:

\begin{align}
\boldsymbol{u} & = A\boldsymbol{x} \\
y & = \|\boldsymbol{u}-\boldsymbol{b}\|^2 = (\boldsymbol{u}-\boldsymbol{b})^T(\boldsymbol{u}-\boldsymbol{b})
\end{align}

where $\boldsymbol{x} \in \mathbb{R}^{n \times 1}$, $\boldsymbol{u} \in \mathbb{R}^{m \times 1}$, $\boldsymbol{b} \in \mathbb{R}^{m \times 1}$ are represented as column vectors and $\boldsymbol{b}$ is a constant vector.

Thus, the gradient can be computed as:

\begin{align}
\frac{\partial{\boldsymbol{u}}}{\partial{\boldsymbol{x}}} & = A \\
\frac{\partial{y}}{\partial{\boldsymbol{u}}} & = (\boldsymbol{u} - \boldsymbol{b})^T \\
\frac{\partial{y}}{\partial{\boldsymbol{x}}} & = (\boldsymbol{u} - \boldsymbol{b})^T A
\end{align}

In [0]:
np.random.seed(1234)
x = np.random.normal(loc=0, scale=1, size=(3, 1))
A = np.random.normal(loc=0, scale=1, size=(2, 3))
u = np.matmul(A, x)
b = np.random.normal(loc=0, scale=1, size=(2, 1))
y = np.linalg.norm(u - b, ord=2) ** 2

print('x = \n', x)
print('A = \n', A)
print('u = \n', u)
print('b = \n', b)
print('y = \n', y)

x = 
 [[ 0.47143516]
 [-1.19097569]
 [ 1.43270697]]
A = 
 [[-0.3126519  -0.72058873  0.88716294]
 [ 0.85958841 -0.6365235   0.01569637]]
u = 
 [[1.9818531 ]
 [1.18581253]]
b = 
 [[-2.24268495]
 [ 1.15003572]]
y = 
 17.84800171888922


In [0]:
udx = A
ydu = (u - b).transpose((1,0))
ydx = np.matmul(ydu, udx)

print('gradient of u to x = \n', udx)
print('gradient of y to u = \n', ydu)
print('gradient of y to x = \n', ydx)

gradient of u to x = 
 [[-0.3126519  -0.72058873  0.88716294]
 [ 0.85958841 -0.6365235   0.01569637]]
gradient of y to u = 
 [[4.22453805 0.0357768 ]]
gradient of y to x = 
 [[-1.29005651 -3.0669273   3.74841516]]


# Linear regression with a single instance


Using gradient descent algorithm to optimize the objective function

In [0]:
# for a univariate problem with a single instance
def opt(niter=10, alpha=0.1):
    w=0.1
    c1=1; c2=-1; c3=1  # computed from the data instance
    for i in range(niter):
        # print J(w)=w*w*c1+w*c2+c3
        Jw = w*w*c1+w*c2+c3
        print('Jw={}'.format(Jw))
        
        # compute the gradient of J(w) with respect to w
        gw = 2*w*c1 + c2
        
        # update w
        w = w - alpha * gw  

opt()

Jw=0.91
Jw=0.8524
Jw=0.815536
Jw=0.79194304
Jw=0.7768435456
Jw=0.7671798691839999
Jw=0.76099511627776
Jw=0.7570368744177665
Jw=0.7545035996273705
Jw=0.7528823037615171


In [0]:
# for a multivariate problem with a single instance
def opt(niter=10, alpha=0.01):
    w = np.random.rand(3)
    x = np.array([3, 4, 5])  # feature
    y = 0.9                  # target value
    for i in range(niter):
        # print J(w)=0.5*(np.dot(x, w) - y)**2
        Jw = 0.5*(np.dot(x, w) - y)**2
        print('Jw={}'.format(Jw))
        
        # compute the gradient of J(w) with respect to w
        gw = (np.dot(x, w) - y) * x
        
        # update w
        w = w - alpha * gw

opt() 

Jw=12.355186044755918
Jw=3.0887965111889795
Jw=0.7721991277972449
Jw=0.19304978194931127
Jw=0.048262445487327735
Jw=0.01206561137183196
Jw=0.0030164028429579856
Jw=0.0007541007107394986
Jw=0.00018852517768487247
Jw=4.713129442121974e-05


# Linear regression with multiple instances

We assume the data is generated via

$$ y = w^Tx $$
where w=[0.1, 2, 0.2]

In [0]:
rng = np.random.RandomState(1)
X = 5 * rng.rand(50, 3)
w = np.array([0.1, 2., 0.2])   # ground truth w
y = np.matmul(X, w) + rng.randn(50)
print(X.shape, y.shape)

(50, 3) (50,)


In [0]:

class MyLRModel():
  def __init__(self, niter=50, alpha=0.03):
    self.niter = niter
    self.alpha = alpha
    
  def fit(self, X, y):
    m, n = X.shape    
    self.w = np.random.rand(n)  # initialize w
    
    for i in range(self.niter):
      # Compute loss 
      Jw = 0.5 * np.average((np.matmul(X, self.w) - y)**2)
      print('Jw = {}'.format(Jw))
        
      # Compute the gradient 
      gw = 1 / m * np.matmul(X.T, np.matmul(X, self.w) - y)
        
      # Update self.w
      self.w = self.w - self.alpha * gw
      
      
    self.coef_ = self.w
    # self.intercept_ = self.b

      
  def predict(self, X):
      return np.matmul(X, self.w) 


model = MyLRModel()

model.fit(X, y)
print(model.w)



Jw = 5.737387285352593
Jw = 3.0507503964122873
Jw = 2.3260674670940507
Jw = 1.9746107422778911
Jw = 1.7229782779069551
Jw = 1.5192865475577642
Jw = 1.3497550392445203
Jw = 1.2078192090151167
Jw = 1.0888198162625864
Jw = 0.9889989858771994
Jw = 0.9052364908315398
Jw = 0.8349257435424461
Jw = 0.7758863174398024
Jw = 0.7262935534054015
Jw = 0.6846201880908818
Jw = 0.6495876479562321
Jw = 0.6201253548679034
Jw = 0.5953367142618993
Jw = 0.5744706846815408
Jw = 0.5568980104059847
Jw = 0.5420913504002853
Jw = 0.529608663142417
Jw = 0.5190793123449605
Jw = 0.5101924466598976
Jw = 0.5026872800083169
Jw = 0.4963449606083716
Jw = 0.4909817680841854
Jw = 0.4864434208949856
Jw = 0.4826003121215031
Jw = 0.47934352154948473
Jw = 0.4765814769698888
Jw = 0.4742371584834698
Jw = 0.4722457570316611
Jw = 0.470552712941749
Jw = 0.46911207244488146
Jw = 0.4678851102950102
Jw = 0.46683917511500794
Jw = 0.4659467211981074
Jw = 0.4651844964283198
Jw = 0.4645328609445635
Jw = 0.46397521532019537
Jw = 0.46349752